"""Seed corpus management — provenance tracking, minimization, priority.

Manages the shared seed corpus across differential targets, tracks whether
seeds originated from AFL++ mutations or LLM generation, and maintains
a priority queue for LLM-generated seeds.
"""

from __future__ import annotations

import dataclasses
import hashlib
import logging
import shutil
import time
from enum import Enum
from pathlib import Path

logger = logging.getLogger(__name__)


class SeedOrigin(str, Enum):
    """Provenance of a seed input."""
    INITIAL = "initial"         # from the initial seed corpus
    AFL_MUTATION = "afl"        # generated by AFL++ mutation
    LLM_GENERATED = "llm"      # generated by the LLM mutator
    LLM_CRASH = "llm_crash"    # suggested by LLM crash analyzer
    MANUAL = "manual"           # manually added by user


@dataclasses.dataclass
class SeedEntry:
    """A single seed in the corpus."""
    seed_id: str
    file_path: Path
    data: bytes
    origin: SeedOrigin
    created_at: float = dataclasses.field(default_factory=time.time)
    hit_new_coverage: bool = False
    new_edges_count: int = 0
    rationale: str = ""


class CorpusManager:
    """Manages the fuzzing seed corpus across all targets.

    Responsibilities:
    - Shared corpus directory that all AFL++ instances read from
    - Provenance tracking (LLM vs AFL vs initial)
    - Seed deduplication by content hash
    - Statistics on seed effectiveness
    """

    def __init__(self, corpus_dir: Path) -> None:
        self._corpus_dir = corpus_dir
        self._corpus_dir.mkdir(parents=True, exist_ok=True)
        self._seeds: dict[str, SeedEntry] = {}
        self._content_hashes: set[str] = set()
        self._counters: dict[SeedOrigin, int] = {origin: 0 for origin in SeedOrigin}

    def load_initial_seeds(self, seeds_dir: Path) -> int:
        """Load seeds from an initial seed directory.

        Copies seeds into the managed corpus directory and registers them.
        Returns the number of seeds loaded.
        """
        if not seeds_dir.exists():
            logger.warning("Seeds directory not found: %s", seeds_dir)
            return 0

        count = 0
        for seed_file in sorted(seeds_dir.iterdir()):
            if seed_file.is_file() and not seed_file.name.startswith("."):
                data = seed_file.read_bytes()
                if self.add_seed(data, SeedOrigin.INITIAL, rationale=f"initial: {seed_file.name}"):
                    count += 1

        logger.info("Loaded %d initial seeds from %s", count, seeds_dir)
        return count

    def add_seed(
        self,
        data: bytes,
        origin: SeedOrigin,
        rationale: str = "",
    ) -> bool:
        """Add a seed to the corpus.

        Returns True if the seed was new (not a duplicate).
        """
        content_hash = hashlib.sha256(data).hexdigest()[:16]

        # Dedup
        if content_hash in self._content_hashes:
            return False

        self._content_hashes.add(content_hash)
        self._counters[origin] = self._counters.get(origin, 0) + 1

        seed_id = f"{origin.value}_{self._counters[origin]:06d}"
        # Use underscores instead of colons for Windows filesystem compatibility
        filename = f"id_{seed_id}_hash_{content_hash}"
        file_path = self._corpus_dir / filename

        file_path.write_bytes(data)

        entry = SeedEntry(
            seed_id=seed_id,
            file_path=file_path,
            data=data,
            origin=origin,
            rationale=rationale,
        )
        self._seeds[content_hash] = entry

        logger.debug("Added seed %s (%d bytes, origin=%s)", seed_id, len(data), origin.value)
        return True

    def add_seeds_batch(
        self,
        seeds: list[bytes],
        origin: SeedOrigin,
        rationale: str = "",
    ) -> int:
        """Add multiple seeds at once. Returns count of new seeds added."""
        added = 0
        for data in seeds:
            if self.add_seed(data, origin, rationale):
                added += 1
        return added

    def record_coverage_hit(self, data: bytes, new_edges: int) -> None:
        """Mark a seed as having hit new coverage."""
        content_hash = hashlib.sha256(data).hexdigest()[:16]
        entry = self._seeds.get(content_hash)
        if entry:
            entry.hit_new_coverage = True
            entry.new_edges_count = new_edges

    # ------------------------------------------------------------------
    # Queries
    # ------------------------------------------------------------------

    def get_recent_seeds(self, n: int = 10, origin: SeedOrigin | None = None) -> list[SeedEntry]:
        """Get the N most recently added seeds, optionally filtered by origin."""
        seeds = list(self._seeds.values())
        if origin:
            seeds = [s for s in seeds if s.origin == origin]
        seeds.sort(key=lambda s: s.created_at, reverse=True)
        return seeds[:n]

    def get_seed_data(self, n: int = 10) -> list[bytes]:
        """Get raw data of the N most recent seeds (for LLM context)."""
        return [s.data for s in self.get_recent_seeds(n)]

    @property
    def total_seeds(self) -> int:
        return len(self._seeds)

    @property
    def stats(self) -> dict:
        llm_seeds = [s for s in self._seeds.values() if s.origin == SeedOrigin.LLM_GENERATED]
        llm_hits = [s for s in llm_seeds if s.hit_new_coverage]
        return {
            "total_seeds": len(self._seeds),
            "by_origin": {origin.value: self._counters.get(origin, 0) for origin in SeedOrigin},
            "llm_seeds": len(llm_seeds),
            "llm_hits": len(llm_hits),
            "llm_hit_rate": (len(llm_hits) / len(llm_seeds) * 100) if llm_seeds else 0,
        }

    @property
    def corpus_dir(self) -> Path:
        return self._corpus_dir
